
headless_cms:
  engine: "decap"
  site_url: ""

  local_backend: true

  backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
    # repo: "emmanuel-io/emmanuel-io.github.io.hugo"
    # collections:
    #   blog:
    #     create: true
    #     fields:
    #       - label: "Title"
    #         name: "title"
    #         widget: "string"
  collections:
    - label: "Blog in English"
      name: "english_posts"
      folder: "_posts"
      create: true
      filter: {field: "language", value: "en"}
      fields:
        - {label: "Language", name: "language", widget: "select", options: ["en", "es"]}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Content", name: "body", widget: "markdown"}