title: Emmanuel IO tech blog
# baseURL: ''
languageCode: en-us
defaultContentLang: en
defaultContentLanguageInSubdir: true
disableLanguages:
  - de
  - es
  - fr

# theme: "paper"
theme: PaperMod
Paginate: 12
googleAnalytics: ''

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
        
# markup:
#   goldmark:
#       renderer:
#           unsafe: true

#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
      disabled: false
      simple: true

  twitter:
      disabled: false
      enableDNT: true
      simple: true

  instagram:
      disabled: false
      simple: true

  youtube:
      disabled: false
      privacyEnhanced: true

services:
  instagram:
      disableInlineCSS: true
  twitter:
      disableInlineCSS: true
